#! /bin/sh

### AUTOSTART ###
sxhkd &
compton --config ~/.config/compton.conf &
wal -a '95' -i ~/Pictures/ &
./panel &

### MONITORS ###
bspc monitor -d I II III

### BSPWM CONFIGURATION ### 
bspc config border_width         1
bspc config window_gap           5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          0.5
bspc config bottom_padding       0.5
bspc config left_padding         0.5
bspc config right_padding        0.5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a URxvt desktop='^1' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Steam desktop='^3' state=floating
